"""Test module v1_calculate."""

import pytest

pytest.importorskip("pysiaf")

import numpy as np  # noqa: E402
from astropy.table import Table  # noqa: E402
from astropy.time import Time  # noqa: E402
from astropy.utils.data import get_pkg_data_filename  # noqa: E402
from stdatamodels.jwst.datamodels import ImageModel  # noqa: E402

import jwst.lib.set_telescope_pointing as stp  # noqa: E402
import jwst.lib.v1_calculate as v1c  # noqa: E402
from jwst.lib import engdb_mast  # noqa: E402

# Mark all tests in this module as slow due to possible remote DB connection
pytestmark = pytest.mark.slow

# The tests here need MAST DB to be available.
try:
    engdb_mast.EngdbMast(base_url=engdb_mast.MAST_BASE_URL)
except RuntimeError as exception:
    pytest.skip(
        f"Live MAST Engineering Service not available: {exception}", allow_module_level=True
    )

# Engineering parameters
# Time range corresponds to OTE-1 exposure jw01134001037_03107_00001_nrcb1_uncal.fits
# Midpoint is about 2022-02-02T22:25:00
MAST_GOOD_STARTTIME = Time("59612.93401553055", format="mjd")
MAST_GOOD_ENDTIME = Time("59612.93500967592", format="mjd")


def test_from_models_mast(tmp_path):
    """Test v1_calculate_from_models for basic running."""
    model = ImageModel()
    model.meta.exposure.start_time = MAST_GOOD_STARTTIME.mjd
    model.meta.exposure.end_time = MAST_GOOD_ENDTIME.mjd

    v1_table = v1c.v1_calculate_from_models(
        [model], method=stp.Methods.COARSE_TR_202111, engdb_url=engdb_mast.MAST_BASE_URL
    )
    v1_formatted = v1c.simplify_table(v1_table)

    # Save for post-test examination
    v1_formatted.write(tmp_path / "test_from_models_mast.ecsv", format="ascii.ecsv")

    truth = Table.read(
        get_pkg_data_filename("data/test_from_models_mast.ecsv", package="jwst.lib.tests")
    )
    errors = v1_compare_simplified_tables(v1_formatted, truth)
    errors_str = "\n".join(errors)
    assert len(errors) == 0, f"V1 tables are different: {errors_str}"


def test_over_time_mast(tmp_path):
    """Test v1_calculate_over_time for basic running."""
    v1_table = v1c.v1_calculate_over_time(
        MAST_GOOD_STARTTIME.mjd,
        MAST_GOOD_ENDTIME.mjd,
        method=stp.Methods.COARSE_TR_202111,
        engdb_url=engdb_mast.MAST_BASE_URL,
    )
    v1_formatted = v1c.simplify_table(v1_table)

    # Save for post-test examination
    v1_formatted.write(tmp_path / "test_over_time_mast.ecsv", format="ascii.ecsv")

    truth = Table.read(
        get_pkg_data_filename("data/test_over_time_mast.ecsv", package="jwst.lib.tests")
    )
    errors = v1_compare_simplified_tables(v1_formatted, truth)
    errors_str = "\n".join(errors)
    assert len(errors) == 0, f"V1 tables are different: {errors_str}"


# ######################
# Fixtures and utilities
# ######################


def v1_compare_simplified_tables(a, b, rtol=1e-05):
    """Calculate diff between tables generated by v1_calculate."""
    errors = []
    if len(a) != len(b):
        errors.append(f"len(a)={len(a)} not equal to len(b)={len(b)}")

    if not all(a["obstime"] == b["obstime"]):
        errors.append("obstimes different")

    if not np.allclose(a["ra"], b["ra"], rtol=rtol):
        errors.append("RAs are different")

    if not np.allclose(a["dec"], b["dec"], rtol=rtol):
        errors.append("DECs are different")

    if not np.allclose(a["pa_v3"], b["pa_v3"], rtol=rtol):
        errors.append("PA_V3s are different")

    return errors
