version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - no-changelog-entry-needed
    target-branch: "main"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"
