breaking-change:
  - changed-files:
      - any-glob-to-any-file:
          - "changes/*.breaking.rst"

documentation:
  - changed-files:
      - all-globs-to-any-file:
          - "*.rst"
          - "!CHANGES.rst"
          - "!changes/*"
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"
          - ".readthedocs.yaml"
          - "LICENSE"
          - "changes/*.docs.rst"

packaging:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"
          - "setup.*"
          - "requirements-*.txt"
          - "MANIFEST.in"

# --------------------------------------- testing ---------------------------------------

automation:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

testing:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/test*.yml"
          - "**/conftest.py"
          - "tox.ini"

# --------------------------------------- general pipeline changes ---------------------------------------

associations:
  - changed-files:
      - any-glob-to-any-file:
          - "**/associations/**/*"
          - "**/scripts/asn_*.py"

datamodels:
  - changed-files:
      - any-glob-to-any-file:
          - "**/datamodels/**/*"

model_blender:
  - changed-files:
      - any-glob-to-any-file:
          - "**/model_blender/**/*"

pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pipeline/**/*"

stpipe:
  - changed-files:
      - any-glob-to-any-file:
          - "**/stpipe/**/*"

# --------------------------------------- step changes ---------------------------------------

adaptive_trace_model:
  - changed-files:
      - any-glob-to-any-file:
          - "**/adaptive_trace_model/**/*"

align_refs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/coron/align_refs*.py"

ami:
  - changed-files:
      - any-glob-to-any-file:
          - "**/ami/**/*"

assign_mtwcs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/assign_mtwcs/**/*"

assign_wcs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/assign_wcs/**/*"

background:
  - changed-files:
      - any-glob-to-any-file:
          - "**/background/**/*"

badpix_selfcal:
  - changed-files:
      - any-glob-to-any-file:
          - "**/badpix_selfcal/**/*"

barshadow:
  - changed-files:
      - any-glob-to-any-file:
          - "**/barshadow/**/*"

charge_migration:
  - changed-files:
      - any-glob-to-any-file:
          - "**/charge_migration/**/*"

clean_flicker_noise:
  - changed-files:
      - any-glob-to-any-file:
          - "**/clean_flicker_noise/**/*"

combine_1d:
  - changed-files:
      - any-glob-to-any-file:
          - "**/combine_1d/**/*"

cube_build:
  - changed-files:
      - any-glob-to-any-file:
          - "**/cube_build/**/*"

dark_current:
  - changed-files:
      - any-glob-to-any-file:
          - "**/dark_current/**/*"

dq_init:
  - changed-files:
      - any-glob-to-any-file:
          - "**/dq_init/**/*"

emicorr:
  - changed-files:
      - any-glob-to-any-file:
          - "**/emicorr/**/*"

engdb_tools:
  - changed-files:
      - any-glob-to-any-file:
          - "**/lib/engdb_*.py"

exp_to_source:
  - changed-files:
      - any-glob-to-any-file:
          - "**/exp_to_source/**/*"

extract_1d:
  - changed-files:
      - any-glob-to-any-file:
          - "**/extract_1d/**/*"

extract_2d:
  - changed-files:
      - any-glob-to-any-file:
          - "**/extract_2d/**/*"

firstframe:
  - changed-files:
      - any-glob-to-any-file:
          - "**/firstframe/**/*"

flatfield:
  - changed-files:
      - any-glob-to-any-file:
          - "**/flatfield/**/*"

fringe:
  - changed-files:
      - any-glob-to-any-file:
          - "**/fringe/**/*"

gain_scale:
  - changed-files:
      - any-glob-to-any-file:
          - "**/gain_scale/**/*"

group_scale:
  - changed-files:
      - any-glob-to-any-file:
          - "**/group_scale/**/*"

guider_cds:
  - changed-files:
      - any-glob-to-any-file:
          - "**/guider_cds/**/*"

imprint:
  - changed-files:
      - any-glob-to-any-file:
          - "**/imprint/**/*"

ipc:
  - changed-files:
      - any-glob-to-any-file:
          - "**/ipc/**/*"

jump:
  - changed-files:
      - any-glob-to-any-file:
          - "**/jump/**/*"

lastframe:
  - changed-files:
      - any-glob-to-any-file:
          - "**/lastframe/**/*"

linearity:
  - changed-files:
      - any-glob-to-any-file:
          - "**/linearity/**/*"

master_background:
  - changed-files:
      - any-glob-to-any-file:
          - "**/master_background/**/*"

msaflagopen:
  - changed-files:
      - any-glob-to-any-file:
          - "**/msaflagopen/**/*"

outlier_detection:
  - changed-files:
      - any-glob-to-any-file:
          - "**/outlier_detection/**/*"

pathloss:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pathloss/**/*"

persistence:
  - changed-files:
      - any-glob-to-any-file:
          - "**/persistence/**/*"

photom:
  - changed-files:
      - any-glob-to-any-file:
          - "**/photom/**/*"

picture_frame:
  - changed-files:
      - any-glob-to-any-file:
          - "**/picture_frame/**/*"

pixel_replace:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pixel_replace/**/*"

ramp_fitting:
  - changed-files:
      - any-glob-to-any-file:
          - "**/ramp_fitting/**/*"

refpix:
  - changed-files:
      - any-glob-to-any-file:
          - "**/refpix/**/*"

resample:
  - changed-files:
      - all-globs-to-any-file:
          - "**/resample/**/*"
          - "!**/resample/resample_spec*.py"

resample_spec:
  - changed-files:
      - any-glob-to-any-file:
          - "**/resample/resample_spec*.py"

reset:
  - changed-files:
      - any-glob-to-any-file:
          - "**/reset/**/*"

residual_fringe:
  - changed-files:
      - any-glob-to-any-file:
          - "**/residual_fringe/**/*"

rscd:
  - changed-files:
      - any-glob-to-any-file:
          - "**/rscd/**/*"

saturation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/saturation/**/*"

skymatch:
  - changed-files:
      - any-glob-to-any-file:
          - "**/skymatch/**/*"

source_catalog:
  - changed-files:
      - any-glob-to-any-file:
          - "**/source_catalog/**/*"

spectral_leak:
  - changed-files:
      - any-glob-to-any-file:
          - "**/spectral_leak/**/*"

srctype:
  - changed-files:
      - any-glob-to-any-file:
          - "**/srctype/**/*"

stack_refs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/coron/stack_refs*.py"

straylight:
  - changed-files:
      - any-glob-to-any-file:
          - "**/straylight/**/*"

superbias:
  - changed-files:
      - any-glob-to-any-file:
          - "**/superbias/**/*"

targ_centroid:
  - changed-files:
      - any-glob-to-any-file:
          - "**/targ_centroid/**/*"

tso_photometry:
  - changed-files:
      - any-glob-to-any-file:
          - "**/tso_photometry/**/*"

tweakreg:
  - changed-files:
      - any-glob-to-any-file:
          - "**/tweakreg/**/*"

wavecorr:
  - changed-files:
      - any-glob-to-any-file:
          - "**/wavecorr/**/*"

wfs_combine:
  - changed-files:
      - any-glob-to-any-file:
          - "**/wfs_combine/**/*"

wfss_contam:
  - changed-files:
      - any-glob-to-any-file:
          - "**/wfss_contam/**/*"

white_light:
  - changed-files:
      - any-glob-to-any-file:
          - "**/white_light/**/*"

# --------------------------------------- pipelines ---------------------------------------

detector1 pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pipeline/*detector1.py"

coron3 pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pipeline/*coron3.py"

image2 pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pipeline/*image2.py"

image3 pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pipeline/*image3.py"

spec2 pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pipeline/*spec2.py"

spec3 pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pipeline/*spec3.py"

ami3 pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pipeline/*ami3.py"

tso3 pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pipeline/*tso3.py"

# --------------------------------------- instruments ---------------------------------------

Fine Guidance Sensor (FGS):
  - changed-files:
      - any-glob-to-any-file:
          - "**/assign_wcs/fgs.py"

Mid Infrared Instrument (MIRI):
  - changed-files:
      - any-glob-to-any-file:
          - "**/assign_wcs/miri.py"

Near Infrared Spectrograph (NIRSpec):
  - changed-files:
      - any-glob-to-any-file:
          - "**/assign_wcs/nirspec.py"
          - "**/extract_2d/nirspec.py"
          - "**/master_background/nirspec_utils.py"

Near Infrared Camera (NIRCam):
  - changed-files:
      - any-glob-to-any-file:
          - "**/assign_wcs/nircam.py"

Near Infrared Imager and Slitless Spectrograph (NIRISS):
  - changed-files:
      - any-glob-to-any-file:
          - "**/assign_wcs/niriss.py"

Wide Field Slitless Spec (WFSS):
  - changed-files:
      - any-glob-to-any-file:
          - "**/background/background_sub_wfss.py"
          - "**/datamodels/utils/wfss_multispec.py"
          - "**/wfss_contam/**/*"
