changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Documentation Changes
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
