# yaml-language-server: $schema=https://raw.githubusercontent.com/readthedocs/readthedocs.org/refs/heads/main/readthedocs/rtd_tests/fixtures/spec/v2/schema.json
# https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - htmlzip
  - pdf

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  apt_packages:
    - graphviz
  jobs:
    post_checkout:
      - git fetch --unshallow || true
      - git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*' || true
      - git fetch --all --tags || true
    pre_install:
      - git update-index --assume-unchanged docs/conf.py
    post_install:
      - pip install towncrier
      - git describe --exact-match || towncrier build --keep

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
