#!/bin/sh
cd `dirname $0`


N=32

svn=false
svn=true

which=$1
python=$2

if [ "$which" = "" ]
then
	which=dev
fi

hostname=`hostname`

#eval  `/eng/ssb/auto/steuermann_scripts/iraf.sh $which $python`
source ~/.profile
ssb${which}


PDK_CONTEXT=$which

if $svn 
then
	bin/svnupdate
fi

if ( [ "$DISPLAY" = "" ] || [ "$DISPLAY" = none ]  )
then
	if [ -n "$sm_run" ]; then
            PDK_TESTRUN=jwst_${sm_run}
	else
            echo 'WARNING: $sm_run undefined in this context: using absolute date'
            PDK_TESTRUN=jwst_`date '+%Y-%m-%d'`
	fi
	PDK_LOG=/eng/ssb/tests/pdk_reports/jwst.$which-$hostname.$PDK_CONTEXT.$PDK_TESTRUN
else
	PDK_TESTRUN=user_${USER}_`date '+%Y-%m-%d-%H-%M'`
	PDK_LOG=PDK.$which-$hostname.$PDK_CONTEXT.$PDK_TESTRUN
fi


echo $PDK_TESTRUN
echo $PDK_LOG

HOME=`pwd`

export PDK_TESTRUN
export PDK_LOG
export PDK_CONTEXT
export HOME

. testconfig/default

if [ -f testconfig/$hostname ]
then
	. testconfig/$hostname
fi

bin/clean

echo XXXXXXXXXXXXXXXXXXXX
env | sort
echo XXXXXXXXXXXXXXXXXXXX
echo ''
echo LIST=$list
echo ''

pdkrun --parallel=$N -r $list

st=$?

rm -rf .matplotlib

exit $?
