/ FGS dither pattern (FGS imaging only)

PATT_NUM =   1      /    position number within primary dither pattern
NUMDTHPT =   1      /    number of points in primary dither pattern
SUBPXNUM =   1      /    subpixel sampling pattern number
SUBPXPNS =   1      /    number of points in subpixel dither pattern
XOFFSET  =  0.0     /    x offset from pattern starting position
YOFFSET  =  0.0     /    y offset from pattern starting position

