/ Guide star information

GS_ORDER = 'N/A'  /  index of guide star 
GSSTRTTM = 'N/A'  /  UTC start time of guide star acquisition
GSENDTIM = 'N/A'  /  UTC end time of guide star acquisition
GDSTARID = 'N/A'  /  guide star identifier
GS_RA    = 'N/A'  /  guide star right ascension
GS_DEC   = 'N/A'  /  guide star declination
GSURA    = 'N/A'  /  guide star right ascension uncertainty
GSUDEC   = 'N/A'  /  guide star declination uncertainty
GS_MAG   = 'N/A'  /  guide star magnitude in FGS detector
GSUMAG   = 'N/A'  /  guide star magnitude uncertainty
PCS_MODE = 'N/A'  /  Pointing Control System mode
GSCENTX  = 'N/A'  /  guide star centroid x position
GSCENTY  = 'N/A'  /  guide star centroid y position
JITTERMS = 'N/A'  /  [arcsec] RMS jitter over the exposure

