/ Guide star information

GS_ORDER =   1    /  index of guide star 
GSSTRTTM = 'N/A'  /  UTC start time of guide star acquisition
GSENDTIM = 'N/A'  /  UTC end time of guide star acquisition
GDSTARID = 'N/A'  /  guide star identifier
GS_RA    = 0.0    /  guide star right ascension
GS_DEC   = 0.0    /  guide star declination
GSURA    = 0.0    /  guide star right ascension uncertainty
GSUDEC   = 0.0    /  guide star declination uncertainty
GS_MAG   = 0.0    /  guide star magnitude in FGS detector
GSUMAG   = 0.0    /  guide star magnitude uncertainty
PCS_MODE = 'FINEGUIDE'  /  Pointing Control System mode
GSCENTX  = 0.0    /  guide star centroid x position
GSCENTY  = 0.0    /  guide star centroid y position
JITTERMS = 0.0    /  [arcsec] RMS jitter over the exposure

