/ JWST ephemeris information

COORDSYS  = 'N/A'  /         ephemeris coordinate system
EPH_TIME  =  0.0   /         [sec] UTC time from ephemeris start time
JWST_X    =  0.0   /         [km] X spatial coordinate of JWST 
JWST_Y    =  0.0   /         [km] Y spatial coordinate of JWST
JWST_Z    =  0.0   /         [km] Z spatial coordinate of JWST
JWST_DX   =  0.0   /         [km/sec] X component of JWST velocity vector
JWST_DY   =  0.0   /         [km/sec] Y component of JWST velocity vector
JWST_DZ   =  0.0   /         [km/sec] Z component of JWST velocity vector

