/ MIRI imaging dither pattern (MIRI imaging only)

PATTTYPE  = 'NONE' /        primary dither pattern type
PATT_NUM  =   1    /        position number within primary dither pattern
PATTSTRT  =   1    /        starting point in the dither pattern
NUMDTHPT  =   1    /        number of points in primary dither pattern
PATTSIZE  =  '0.0'   /        primary dither pattern size
SUBPIXEL  =   F    /        subpixel sampling performed (T/F)
SUBPXNUM  =   1    /        subpixel sampling pattern number
XOFFSET   =  0.0   /        x offset from pattern starting position 
YOFFSET   =  0.0   /        y offset from pattern starting position 

