/ MIRI LRS dither pattern (MIRI LRS only)

PATTTYPE  = 'NONE' / dither pattern type
PATT_NUM  =   1    / position number within dither pattern
NUMDTHPT  =   1    / total number of points in dither pattern
SPEC_NUM  = 'N/A'  / position number within spectral steps
SPECNSTP  = 'N/A'  / total number of steps in the spectral direction
SPECSTEP  = 'N/A'  / [arcsec] distance between steps in the spectral direction 
SPCOFFST  = 'N/A'  / [arcsec] spectral offset from pattern starting position 
SPAT_NUM  = 'N/A'  / position number within spatial steps
SPATNSTP  = 'N/A'  / total number of steps in the spatial direction
SPATSTEP  = 'N/A'  / [arcsec] distance between steps in the spatial direction 
SPTOFFST  = 'N/A'  / [arcsec] spatial offset from pattern starting position 

