/ subarray parameters

SUBARRAY  = 'FULL'    /  subarray used
SUBSTRT1  = 1         /  starting pixel number in the SIAS x direction
SUBSIZE1  = 2048      /  number of pixels in the SIAS x direction
SUBSTRT2  = 1         /  starting pixel number in the SIAS y direction
SUBSIZE2  = 2048      /  number of pixels in the SIAS y direction
NXLIGHT   = 2040      /  number of light sensitive columns
FASTAXIS  = input()   /  Axis and direction of fast readout
SLOWAXIS  = input()   /  Axis and direction of slow readout
