/ NIRCam dither pattern (NIRCam only)

PATTTYPE  = 'NONE' /      primary dither pattern type
PATT_NUM  =   1    /      position number within primary dither pattern
NUMDTHPT  =   1    /      total number of points in primary dither pattern
PATTSIZE  =  '0.0'   /      [arcsec] primary dither pattern size 
SUBPXTYP  = 'N/A'  /      subpixel dithering pattern type
SUBPXNUM  =   1    /      subpixel sampling pattern number
SUBPXPNS  =   1    /      total number of points in subpixel dither pattern
XOFFSET   =  0.0   /      [arcsec] x offset from pattern starting position 
YOFFSET   =  0.0   /      [arcsec] y offset from pattern starting position 

