/ NIRCam WFS&C engineering keywords (NIRCam WFS&C only)

FAM_LA1   = 'N/A'  /       position in steps of linear actuator 1
FASTEP1   = 'N/A'  /       requested focus actuator 1 starting steps
FAUNIT1   = 'N/A'  /       requested focus actuator 1 starting units
FAPHASE1  = 'N/A'  /       requested focus actuator 1 starting phase
FA1VALUE  = 'N/A'  /       requested focus actuator 1 position value
FAM_LA2   = 'N/A'  /       position in steps of linear actuator 2
FASTEP2   = 'N/A'  /       requested focus actuator 2 starting steps
FAUNIT2   = 'N/A'  /       requested focus actuator 2 starting units
FAPHASE2  = 'N/A'  /       requested focus actuator 2 starting phase
FA2VALUE  = 'N/A'  /       requested focus actuator 2 position value
FAM_LA3   = 'N/A'  /       position in steps of linear actuator 3
FASTEP3   = 'N/A'  /       requested focus actuator 3 starting steps 
FAUNIT3   = 'N/A'  /       requested focus actuator 3 starting units 
FAPHASE3  = 'N/A'  /       requested focus actuator 3 starting phase
FA3VALUE  = 'N/A'  /       requested focus actuator 3 position value

