/ NIRSpec target acquisition files (NIRSpec only)

REFSTRFL = '#TODO'   /   reference star file name
TACQSLIT = '#TODO'   /   target acquisition illuminated slit image file name
TACQ1IMG = '#TODO'   /   first target acquisition image file name
TACQ2IMG = '#TODO'   /   second target acquisition image file name
TACNFIMG = '#TODO'   /   target acquisition confirmation image file name
SCCNFIMG = '#TODO'   /   science confirmation image file name

