/ NIRSpec IFU dither pattern (NIRSpec IFU only)

PATT_NUM  =   1   /      position number within dither pattern
NUMDTHPT  =   1   /      total number of points in dither pattern
SLIT_OFF  = 'N/A' /      number of slitlet offsets in the spectral direction
SUBPXTYP  = 'N/A' /      type of sub-pixel offset
SPEC_OFF  = 'N/A' /      [arcsec] spectral offset from IFU aperture center 
SPAT_OFF  = 'N/A' /      [arcsec] spatial offset from IFU aperture center 

