/ Spacecraft ephemeris keywords
EPH_TIME = now() / UTC time from ephemeris start time
X        = 0.0 / X spatial coordinate of JWST (km)
Y        = 0.0 / Y spatial coordinate of JWST (km)
Z        = 0.0 / Z spatial coordinate of JWST (km)
DX       = 0.0 / X component of JWST velocity vector (km/sec)
DY       = 0.0 / Y component of JWST velocity vector (km/sec)
DZ       = 0.0 / Z component of JWST velocity vector (km/sec)
