/ Reference Pixel/Output parameters

REFPIXEL  = input()     / T if reference pixels present, F if not
TREFROW   = input()     / Top reference pixel rows
BREFROW   = input()     / Bottom reference pixel rows
LREFCOL   = input()     / Left column reference pixels
RREFCOL   = input()     / Right column reference pixels
REFIMG    = input()     / T if reference image present, F if not
NREFIMG   = input()     / number of reference rows added to end
NXREFIMG  = input()     / reference image columns
NYREFIMG  = input()     / reference image rows
