/ subarray parameters

SUBARRAY  = input()    /  name of subarray used
SUBSTRT1  = int(float(input('COLSTART'))) /  starting pixel number in the SIAS x direction
SUBSIZE1  = int(input('NAXIS1'))   /  number of pixels in the SIAS x direction
SUBSTRT2  = int(float(input('ROWSTART'))) /  starting pixel number in the SIAS y direction
SUBSIZE2  = int(input('NAXIS2'))   /  number of pixels in the SIAS y direction
NXLIGHT   = '#TODO'     /  number of light sensitive x values (columns)
FASTAXIS  = input()     /  Axis and direction of fast readout
SLOWAXIS  = input()     /  Axis and direction of slow readout
