/ Target information

TARGPROP = input('TARGNAME') / proposer's name for the target
TARGNAME = 'NGC 104' / standard astronomical catalog name for target
TARGTYPE = 'FIXED' / fixed target, moving target, or generic target
TARG_RA  = 0.0 / target RA computed at time of exposure
TARGURA  = 0.0 / target RA uncertainty
TARG_DEC = 0.0 / target DEC computed at time of exposure
TARRUDEC =  0.0  / target Dec uncertainty
PROP_RA  =  0.0  / proposer specified RA for the target
PROP_DEC =  0.0  / proposer specified Dec for the target
PROPEPOC = 2000.0  / proposer specified epoch for RA and Dec

