/ Time related keywords

BARTDELT  =  0.0  / calculated Barycentric time correction
BSTRTIME  =  0.0  / Solar System Barycentric exposure start time
BENDTIME  =  0.0  / Solar System Barycentric exposure end time
BMIDTIME  =  0.0  / Solar System Barycentric exposure mid time
HELIDELT  =  0.0  / calculated Heliocentric time correction
HSTRTIME  =  0.0  / Heliocentric exposure start time in MJD
HENDTIME  =  0.0  / Heliocentric exposure end time in MJD
HMIDTIME  =  0.0  / Heliocentric exposure mid time in MJD

