/ Visit information

VISITYPE = 'GENERIC' / type of visit 
VSTSTART = input('DATE')   / UTC visit start time
WFSVISIT = 'NO' / wavefront sensing and control visit indicator
NEXPOSUR = 1    / total number of exposures in visit
INTARGET = T    / T if at least one exposure in visit is internal
EXTARGET = T    / T if at least one exposure in visit is external
TARGOOPP = F    / visit scheduled as target of opportunity (T/F)

