/ SCI image extension WCS keywords
WCSAXES = 2 / Number of WCS axes
RADESYS = 'IRCS' / Reference frame of coordinates
CRPIX1  = 0 / x-coordinate of the reference pixel
CRPIX2  = 0 / y-coordinate of the reference pixel
CRVAL1  = 0 / First axis value at the reference pixel
CRVAL2  = 0 / Second axis value at the reference pixel
CTYPE1  = 'RA---TAN'
CTYPE2  = 'DEC--TAN'
CD1_1   = 0.0
CD1_2   = 0.0
CD2_1   = 0.0
CD2_2   = 0.0
