
/ WCS parameters

WCSAXES  = 2       /      number of World Coordinate System axes
CRPIX1   = 'N/A' /      x-coordinate of the reference pixel
CRPIX2   = 'N/A' /      y-coordinate of the reference pixel
CRVAL1   = 'N/A' /      RA at the reference pixel(degrees)
CRVAL2   = 'N/A' /      Declination at the reference pixel (degrees)
CTYPE1   = 'RA---TAN'  /  first axis coordinate type
CTYPE2   = 'DEC--TAN'  /  second axis coordinate type
CDELT1   = 'N/A' /      increment per pixel, increasing eastward
CDELT2   = 'N/A' /      increment per pixel, increasing northward
PC1_1    = 'N/A' /      linear transformation matrix element
PC1_2    = 'N/A' /      linear transformation matrix element
PC2_1    = 'N/A' /      linear transformation matrix element
PC2_2    = 'N/A' /      linear transformation matrix element
S_REGION = 'N/A' /      spatial extent of the observation
