#!/usr/bin/env python

"""asn_gather: Copy or Move data that is listed in an association"""

from jwst.associations import asn_gather

if __name__ == 'main':
    path, kwargs = asn_gather.from_cmdline()
    asn_gather.asn_gather(path, **kwargs)
