#!/usr/bin/env python
# ExampleStep

import sys  # rij

import flat_field  #dg

# Import the custom step
from flat_field import flat_field_step

# Import stpipe.cmdline
from stpipe import cmdline

if __name__ == '__main__':
    # Pass the step class to cmdline.step_script
    cmdline.step_script(flat_field_step)
