#!/usr/bin/env python

import sys
import jwst.stpipe as stpipe
from jwst.stpipe import Step

if __name__ == '__main__':

    if '--version' in sys.argv:
        sys.stdout.write("%s\n" % stpipe.__version__)
        sys.exit(0)

    try:
        step = Step.from_cmdline(sys.argv[1:])
    except Exception as e:
        import traceback
        traceback.print_exc()
        sys.exit(1)
