#!/usr/bin/env python
"""V1 Calculation based on time and engineering database info
"""
import argparse
import logging
from sys import stdout

from jwst.lib import v1_calculate

log_handler = logging.StreamHandler()
logger = logging.getLogger('jwst.lib.pointing_summary')
logger.addHandler(log_handler)
LogLevels = [logging.WARNING, logging.INFO, logging.DEBUG]


# Begin execution
if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description='Calculate V1 over a time period.'
    )

    parser.add_argument(
        'exposures', type=str, nargs='+',
        help='List of JWST data files to examine.'
    )
    parser.add_argument(
        '-o', '--output', type=argparse.FileType('w'), default=stdout,
        help='File to write V1 calculation table to. Default is standard output.'
    )
    parser.add_argument(
        '-v', '--verbose', action='count', default=0,
        help='Increase verbosity. Specifying multiple times adds more output.'
    )

    args = parser.parse_args()

    # Set output detail.
    level = LogLevels[min(len(LogLevels)-1, args.verbose)]
    logger.setLevel(level)

    # Process the file list.
    logger.info('Starting V1 calculation...')
    deltas = v1_calculate.v1_calculate_from_models(args.exposures)
    deltas.write(args.output, format='ascii.ecsv')
    logger.info('...V1 calculation completed.')
