Reference Selection Keywords for ABVEGA_OFFSET
++++++++++++++++++++++++++++++++++++++++++++++

CRDS selects appropriate ABVEGA_OFFSET references based on the
following keywords.  ABVEGA_OFFSET is not applicable for instruments
not in the table.  All keywords used for file selection are
*required*.

========== ======================================
Instrument Keywords
========== ======================================
FGS        INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
MIRI       INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
NIRCam     INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
NIRISS     INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
========== ======================================
