Reference Selection Keywords for ABVEGAOFFSET
+++++++++++++++++++++++++++++++++++++++++++++

CRDS selects appropriate ABVEGAOFFSET references based on the
following keywords.  ABVEGAOFFSET is not applicable for instruments
not in the table.  All keywords used for file selection are
*required*.

========== ======================================
Instrument Keywords
========== ======================================
FGS        INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
MIRI       INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
NIRCam     INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
NIRISS     INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
========== ======================================
