.. _bkg_selectors:

Reference Selection Keywords for BKG
++++++++++++++++++++++++++++++++++++
CRDS selects appropriate BKG references based on the following keywords.
BKG is not applicable for instruments not in the table.

========== ===============================================================
Instrument Keywords                                                        
========== ===============================================================
NIRCam     INSTRUME, EXP_TYPE, DETECTOR, FILTER, PUPIL, DATE-OBS, TIME-OBS 
NIRISS     INSTRUME, EXP_TYPE, DETECTOR, FILTER, PUPIL, DATE-OBS, TIME-OBS 
========== ===============================================================

