.. _dark_selectors:

Reference Selection Keywords for DARK
+++++++++++++++++++++++++++++++++++++
CRDS selects appropriate DARK references based on the following keywords.
DARK is not applicable for instruments not in the table.

========== ==================================================================================================
Instrument Keywords
========== ==================================================================================================
FGS        INSTRUME, DETECTOR, READPATT, SUBARRAY, DATE-OBS, TIME-OBS
MIRI       INSTRUME, DETECTOR, READPATT, SUBARRAY, DATE-OBS, TIME-OBS
NIRCam     INSTRUME, DETECTOR, EXP_TYPE, NOUTPUTS, SUBARRAY, DATE-OBS, TIME-OBS
NIRISS     INSTRUME, DETECTOR, READPATT, SUBARRAY, DATE-OBS, TIME-OBS
NIRSpec    INSTRUME, DETECTOR, READPATT, SUBARRAY, SUBSTRT1, SUBSTRT2, SUBSIZE1, SUBSIZE2, DATE-OBS, TIME-OBS
========== ==================================================================================================

