.. _drizpars_selectors:

Reference Selection Keywords for DRIZPARS
+++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate DRIZPARS references based on the following keywords.
DRIZPARS is not applicable for instruments not in the table.
All keywords used for file selection are *required*.

========== ========
Instrument Keywords
========== ========
MIRI       INSTRUME
NIRCam     INSTRUME
NIRISS     INSTRUME
========== ========

