Reference Selection Keywords for EMICORR
++++++++++++++++++++++++++++++++++++++++

CRDS selects appropriate EMICORR references based on the
following keywords.  EMICORR is not applicable for instruments
not in the table.  All keywords used for file selection are
*required*.

========== ============================
Instrument Keywords
========== ============================
MIRI       INSTRUME, DATE-OBS
========== ============================
