.. _extract1d_selectors:

Reference Selection Keywords for EXTRACT1D
++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate EXTRACT1D references based on the following keywords.
EXTRACT1D is not applicable for instruments not in the table.
All keywords used for file selection are *required*.

========== ====================================================
Instrument Keywords
========== ====================================================
MIRI       INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
NIRISS     INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
NIRSpec    INSTRUME, EXP_TYPE, LAMP, OPMODE, DATE-OBS, TIME-OBS
========== ====================================================

