.. _fringefreq_selectors:

Reference Selection Keywords for FRINGEFREQ
+++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate FRINGEFREQ reference file based on the following keywords.
FRINGEFREQ is not applicable for instruments not in the table.

========== ================================================
Instrument Keywords                               
========== ================================================
MIRI       INSTRUME, EXP_TYPE, DETECTOR, DATE-OBS, TIME-OBS 
========== ================================================

