Reference Selection Keywords for GAIN
+++++++++++++++++++++++++++++++++++++
CRDS selects appropriate GAIN references based on the following keywords.
GAIN is not applicable for instruments not in the table.
All keywords used for file selection are *required*.

========== ================================================
Instrument Keywords
========== ================================================
FGS        INSTRUME, DETECTOR, SUBARRAY, DATE-OBS, TIME-OBS
MIRI       INSTRUME, DETECTOR, SUBARRAY, DATE-OBS, TIME-OBS
NIRCam     INSTRUME, DETECTOR, SUBARRAY, DATE-OBS, TIME-OBS
NIRISS     INSTRUME, DETECTOR, SUBARRAY, DATE-OBS, TIME-OBS
NIRSpec    INSTRUME, DETECTOR, SUBARRAY, DATE-OBS, TIME-OBS
========== ================================================
