.. _mrsptcorr_selectors:

Reference Selection Keywords for MRSPTCORR
++++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate MRSPTCORR references based on the following keywords.
MRSPTCORR is not applicable for instruments not in the table.

========== ======================================
Instrument Keywords                               
========== ======================================
MIRI       INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
========== ======================================

