.. _mrsxartcorr_selectors:

Reference Selection Keywords for MRSXARTCORR
++++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate MRSXARTCORR references based on the following keywords.
MRSXARTCORR is not applicable for instruments not in the table.

========== ======================================
Instrument Keywords                               
========== ======================================
MIRI       INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
========== ======================================

