.. _nrm_selectors:

Reference Selection Keywords for NRM
++++++++++++++++++++++++++++++++++++
CRDS selects appropriate NRM references based on the following keywords.
NRM is not applicable for instruments not in the table.
All keywords used for file selection are *required*.

========== ================================================
Instrument Keywords                                         
========== ================================================
NIRISS     INSTRUME, DATE-OBS, TIME-OBS           
========== ================================================