.. _pars_detector1pipeline_reffile:

PARS-DETECTOR1PIPELINE Parameter Reference File
-----------------------------------------------

:REFTYPE: PARS-DETECTOR1PIPELINE
:Data model: N/A

Reference Selection Keywords
++++++++++++++++++++++++++++
CRDS selects appropriate pars-detector1pipeline references based on the following keywords.

========== ======================================
Instrument Keywords
========== ======================================
FGS        TSOVISIT
MIRI       TSOVISIT
NIRCAM     TSOVISIT
NIRISS     TSOVISIT
NIRSPEC    TSOVISIT
========== ======================================

.. include:: ../includes/standard_keywords.inc
