.. _pars_outlierdetectionstep_reffile:

PARS-OUTLIERDETECTIONSTEP Parameter Reference File
--------------------------------------------------

:REFTYPE: PARS-OUTLIERDETECTIONSTEP
:Data model: N/A

Reference Selection Keywords
++++++++++++++++++++++++++++
CRDS selects appropriate pars-outlierdetectionstep references based on the following keywords.

========== ====================================
Instrument Keywords
========== ====================================
FGS        EXP_TYPE
MIRI       EXP_TYPE, FILTER, SUBARRAY, TSOVISIT
NIRCAM     EXP_TYPE, FILTER, PUPIL, TSOVISIT
NIRISS     EXP_TYPE, FILTER, PUPIL, TSOVISIT
========== ====================================

.. include:: ../includes/standard_keywords.inc
