.. _pars_whitelightstep_reffile:

PARS-WHITELIGHTSTEP Parameter Reference File
--------------------------------------------

:REFTYPE: PARS-WHITELIGHTSTEP
:Data model: N/A

Reference Selection Keywords
++++++++++++++++++++++++++++
CRDS selects appropriate pars-whitelightstep references based on the following keywords.

========== ====================================
Instrument Keywords
========== ====================================
MIRI       EXP_TYPE
NIRCAM     EXP_TYPE, FILTER, PUPIL
NIRSPEC    EXP_TYPE
========== ====================================

.. include:: ../includes/standard_keywords.inc
