.. _pars_sourcecatalogstep_reffile:

PARS-SOURCECATALOGSTEP Parameter Reference File
-----------------------------------------------

:REFTYPE: PARS-SOURCECATALOGSTEP
:Data model: N/A

Reference Selection Keywords
++++++++++++++++++++++++++++
CRDS selects appropriate pars-sourcecatalogstep references based on the following keywords.

========== ====================================
Instrument Keywords
========== ====================================
FGS        EXP_TYPE
MIRI       EXP_TYPE, FILTER
NIRCAM     EXP_TYPE, FILTER
NIRISS     EXP_TYPE, FILTER
========== ====================================

.. include:: ../includes/standard_keywords.inc
