.. _pars_tweakregstep_reffile:

PARS-TWEAKREGSTEP Parameter Reference File
------------------------------------------

:REFTYPE: PARS-TWEAKREGSTEP
:Data model: N/A

Reference Selection Keywords
++++++++++++++++++++++++++++
CRDS selects appropriate pars-tweakregstep references based on the following keywords.

========== ====================================
Instrument Keywords
========== ====================================
FGS        EXP_TYPE
MIRI       EXP_TYPE, FILTER
NIRCAM     EXP_TYPE, FILTER, PUPIL
NIRISS     EXP_TYPE, FILTER, PUPIL
========== ====================================

.. include:: ../includes/standard_keywords.inc
