.. _pars_darkpipeline_reffile:

PARS-DARKPIPELINE Reference File
--------------------------------

:REFTYPE: PARS-DARKPIPELINE
:Data model: N/A

Reference Selection Keywords
++++++++++++++++++++++++++++
CRDS selects appropriate pars-whitelightstep references based on the following keywords.

========== ====================================
Instrument Keywords
========== ====================================
FGS        INSTRUME
MIRI       INSTRUME
NIRCAM     INSTRUME
NIRISS     INSTRUME
NIRSPEC    INSTRUME
========== ====================================

.. include:: ../includes/standard_keywords.inc
