.. _pars_image2pipeline_reffile:

PARS-IMAGE2PIPELINE Parameter Reference File
-----------------------------------------------

:REFTYPE: PARS-IMAGE2PIPELINE
:Data model: N/A

Reference Selection Keywords
++++++++++++++++++++++++++++
CRDS selects appropriate pars-image2pipeline references based on the following keywords.

========== ============================
Instrument Keywords
========== ============================
FGS        EXP_TYPE, TSOVISIT, VISITYPE
MIRI       EXP_TYPE, TSOVISIT, VISITYPE
NIRCAM     EXP_TYPE, TSOVISIT, VISITYPE
NIRISS     EXP_TYPE, TSOVISIT, VISITYPE
NIRSPEC    EXP_TYPE, TSOVISIT, VISITYPE
========== ============================

.. include:: ../includes/standard_keywords.inc
