.. _pars_spec2pipeline_reffile:

PARS-SPEC2PIPELINE Parameter Reference File
-----------------------------------------------

:REFTYPE: PARS-SPEC2PIPELINE
:Data model: N/A

Reference Selection Keywords
++++++++++++++++++++++++++++
CRDS selects appropriate pars-spec2pipeline references based on the following keywords.

========== ================================
Instrument Keywords
========== ================================
MIRI       TSOVISIT
NIRCAM     CROWDFLD, EXP_TYPE, TSOVISIT
NIRISS     CROWDFLD, EXP_TYPE, TSOVISIT
NIRSPEC    EXP_TYPE, LAMP, OPMODE, TSOVISIT
========== ================================

.. include:: ../includes/standard_keywords.inc
