.. _pathloss_selectors:

Reference Selection Keywords for PATHLOSS
+++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate PATHLOSS references based on the following keywords.
PATHLOSS is not applicable for instruments not in the table.
All keywords used for file selection are *required*.

========== ======================================
Instrument Keywords                               
========== ======================================
MIRI       INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS 
NIRISS     INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS 
NIRSpec    INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS 
========== ======================================

