.. _pfpc_reffile:

PFPC Reference File
---------------------------

.. todo: add reference to model when it is merged

:REFTYPE: PFPC
:Data model: stdatamodels.jwst.datamodels.PFPCModel

The PFPC reference file contains data necessary for applying a point fixed
pattern correction to dithered spectral data.

.. include:: ../includes/standard_keywords.inc

PFPC Reference File Format
++++++++++++++++++++++++++++++++++

PFPC reference files are in FITS format with one
table extension. The primary HDU does not contain a data array.
The format and content of the file is as follows:

TBD
