Reference Selection Keywords for READNOISE
++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate READNOISE references based on the following keywords.
READNOISE is not applicable for instruments not in the table.
All keywords used for file selection are *required*.

========== ==========================================================
Instrument Keywords
========== ==========================================================
FGS        INSTRUME, DETECTOR, READPATT, SUBARRAY, DATE-OBS, TIME-OBS
MIRI       INSTRUME, DETECTOR, READPATT, SUBARRAY, DATE-OBS, TIME-OBS
NIRCam     INSTRUME, DETECTOR, READPATT, SUBARRAY, DATE-OBS, TIME-OBS
NIRISS     INSTRUME, DETECTOR, READPATT, SUBARRAY, DATE-OBS, TIME-OBS
NIRSpec    INSTRUME, DETECTOR, READPATT, SUBARRAY, DATE-OBS, TIME-OBS
========== ==========================================================
