Reference Selection Keywords for WAVELENGTHRANGE
++++++++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate WAVELENGTHRANGE references based on the following
keywords.
WAVELENGTHRANGE is not applicable for instruments not in the table.
All keywords used for file selection are *required*.

========== ======================================
Instrument Keywords
========== ======================================
MIRI       INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
NIRCam     INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
NIRISS     INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
NIRSpec    INSTRUME, EXP_TYPE, DATE-OBS, TIME-OBS
========== ======================================

