name: build

on:
  pull_request:
  release:
    types: [released]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-tags: true
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3"
      - if: ${{ runner.os == 'Linux' }}
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
        with:
          platforms: all
      - uses: pypa/cibuildwheel@4726cd35bb13f7bde50cf2761f2499ac7b3aa32c # v4.1.1
        with:
          package-dir: ./
          output-dir: dist/
      - run: pip install build
      - run: python -m build --sdist
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist-${{ runner.os }}-${{ runner.arch }}
          path: ./dist/
  publish:
    if: (github.event_name == 'release') && (github.event.action == 'released')
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    # To add required reviewers before deployment,
    # edit the protection rules in GitHub Settings:
    # Settings > Environments > pypi > Add required reviewers
    environment:
      name: pypi
      url: https://pypi.org/p/jwst
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: dist*
          path: dist/
          merge-multiple: true
      - uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        with:
          subject-path: "dist/*"
      # To upload to PyPI without a token, add this workflow file as a Trusted Publisher in the project settings on the PyPI website
      - uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
        with:
          password: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}
