name: Cancel duplicate workflows

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - requested

# Note: This has to be in workflow_run so it works for PRs from forks.  And only cancel
# pull_request triggers, not push, i.e. merges into master.
jobs:
  cancel:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
    - uses: styfle/cancel-workflow-action@0.11.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
