name: changelog

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog-entry-needed') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3"
      - run: pip install . towncrier
      - run: towncrier check
      - name: search for news fragment matching pull request number
        run: towncrier build --draft | grep -P '#${{ github.event.number }}'
