name: Ensure changelog

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  ensure_changelog:
    name: Verify that a changelog entry exists for this pull request
    runs-on: ubuntu-latest
    steps:
    - uses: scientific-python/action-towncrier-changelog@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BOT_USERNAME: changelog-bot

