name: label pull request

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"