name: Publish to PyPI

on:
  release:
    types: [ released ]

jobs:
  check:
    name: check that `requirements-sdp.txt` is populated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: grep -v '^ *#' requirements-sdp.txt
      - run: if [[ -z $(grep -v '^ *#' requirements-sdp.txt) ]]; then echo requirements-sdp.txt is empty; exit 1; fi
  publish:
    needs: [ check ]
    uses: spacetelescope/action-publish_to_pypi/.github/workflows/workflow.yml@master
    with:
      test: false
      build_platform_wheels: true # Set to true if your package contains a C extension
    secrets:
      user: ${{ secrets.PYPI_USERNAME_STSCI_MAINTAINER }}
      password: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }} # WARNING: Do not hardcode secret values here! If you want to use a different user or password, you can override this secret by creating one with the same name in your Github repository settings.
      test_password: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER_TEST }}
