name: extra tests

on:
  pull_request:
    branches:
      - main
      - 'release/*.x'
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  push:
    branches:
      - main
      - 'release/*.x'
    tags:
      - '*'
  schedule:
    - cron: "0 0 * * 1" # every Monday at 6a
  workflow_dispatch:
    inputs:
      crds_context:
        description: CRDS context (leave blank for latest)
        type: string
        required: false
        default: ''
      crds_server:
        description: CRDS server
        type: string
        required: false
        default: https://jwst-crds.stsci.edu

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ inputs.crds_context }}
  cancel-in-progress: true

permissions: {}

env:
  CRDS_PATH: /tmp/data/crds_cache
  CRDS_OBSERVATORY: jwst
  CRDS_SERVER_URL: ${{ inputs.crds_server || 'https://jwst-crds.stsci.edu' }}
  CRDS_CLIENT_RETRY_COUNT: 3
  CRDS_CLIENT_RETRY_DELAY_SECONDS: 20

jobs:
  crds:
    if: (github.repository == 'spacetelescope/jwst' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'run extra tests')))
    runs-on: ubuntu-latest
    steps:
      - if: inputs.crds_context
        id: latest-context
        run: >
          echo latest-context=$(
            curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["${{ env.CRDS_OBSERVATORY }}", "latest"], "id": 1}' ${{ env.CRDS_SERVER_URL }}/json/ --retry 8 --connect-timeout 10 |
            python -c "import sys, json; print(json.load(sys.stdin)['result'])"
          ) >> $GITHUB_OUTPUT
    outputs:
      path: ${{ env.CRDS_PATH }}
      server-url: ${{ env.CRDS_SERVER_URL }}
      context: ${{ inputs.crds_context || steps.latest-context.outputs.latest-context }}
      client-retry-count: ${{ env.CRDS_CLIENT_RETRY_COUNT }}
      client-retry-delay-seconds: ${{ env.CRDS_CLIENT_RETRY_DELAY_SECONDS }}
  test:
    if: (github.repository == 'spacetelescope/jwst' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'run extra tests')))
    needs:
      - crds
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@e5af21e4ae37af089a73bb032e10b78b0e746174 # v3.0.1
    with:
      setenv: |
        CRDS_PATH: ${{ needs.crds.outputs.path }}
        CRDS_SERVER_URL: ${{ needs.crds.outputs.server-url }}
        CRDS_CONTEXT: ${{ needs.crds.outputs.context }}
        CRDS_CLIENT_RETRY_COUNT: ${{ needs.crds.outputs.client-retry-count }}
        CRDS_CLIENT_RETRY_DELAY_SECONDS: ${{ needs.crds.outputs.client-retry-delay-seconds}}
      cache-path: ${{ needs.crds.outputs.path }}
      cache-key: crds-${{ needs.crds.outputs.context }}
      envs: |
        - linux: check-docs-links
        - macos: py*-xdist
        - linux: py3-stdevdeps-xdist
        - linux: py3-devdeps-xdist
        - macos: py3-stdevdeps-xdist
        - macos: py3-devdeps-xdist
      artifact-path: |
        results.xml
